---
name: 🧪 Container Test

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  container-test:
    name: Container Test
    permissions:
      contents: read
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-container-test.yml@f560940f48f870d54b3ce6a318d3548132c5da96 # v6.0.0
