---
name: 📟 PagerDuty Rota Notifier

on:
  schedule:
    - cron: "0 9 * * 1-5" # Monday-Friday at 09:00 UTC
  workflow_dispatch:

permissions: {}

jobs:
  pagerduty-rota-notifier:
    name: PagerDuty Rota Notifier
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - pagerduty-schedule-id: POE95CC # Analytical Platform
            slack-channel: C04M8224WCV # analytical-platform
          - pagerduty-schedule-id: PW7Q2MF # Find Moj Data Daily Support
            slack-channel: C03QZ776JVA # data-catalogue
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Python
        id: setup_python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: 3.12

      - name: Install requirements
        id: install_requirements
        run: |
          pip install --requirement requirements.txt

      - name: Run Script
        id: run_script
        run: |
          python main.py
        env:
          PAGERDUTY_SCHEDULE_ID: ${{ matrix.pagerduty-schedule-id }}
          PAGERDUTY_TOKEN: ${{ secrets.PAGERDUTY_TOKEN }}
          SLACK_CHANNEL: ${{ matrix.slack-channel }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
