---
name: 📟 PagerDuty Rota Notifier

on:
  schedule:
    # - cron: "0 9 * * 1-5" # Monday-Friday at 09:00 UTC
    - cron: "0 8 * * 1-5" # Monday-Friday at 08:00 UTC, or 09:00 BST
  workflow_dispatch:

permissions: {}

jobs:
  pagerduty-rota-notifier:
    name: PagerDuty Rota Notifier
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - pagerduty-schedule-id: POE95CC # Analytical Platform
            slack-channel: C04M8224WCV # analytical-platform
          - pagerduty-schedule-id: PW7Q2MF # Find MoJ Data Daily Support
            slack-channel: C03QZ776JVA # data-catalogue
          - pagerduty-schedule-id: PGMMCDQ # Data Engineering Support HEO_SEO
            slack-channel: CBVUV2613 # data-and-analytics-engineering
          - pagerduty-schedule-id: PAMEXM1 # Data Engineering Support G7
            slack-channel: CBVUV2613 # data-and-analytics-engineering
          - pagerduty-schedule-id: PEZPWMA # Analytics Engineering Support SEO_HEO
            slack-channel: C091ZJEFNL9 # ae-rota-test
          - pagerduty-schedule-id: PHEKY21 # Analytics Engineering Support G7
            slack-channel: C091ZJEFNL9 # ae-rota-test
          - pagerduty-schedule-id: P3MCA8L # em-data-hub-rpta
            slack-channel: C069RF589V4 # em-engineers-moj-madetech
    steps:
      - name: Harden Runner
        id: harden_runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout
        id: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set Up uv
        id: setup_uv
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6.6.1

      - name: Run Script
        id: run_script
        run: |
          uv run main.py
        env:
          PAGERDUTY_SCHEDULE_ID: ${{ matrix.pagerduty-schedule-id }}
          PAGERDUTY_TOKEN: ${{ secrets.PAGERDUTY_TOKEN }}
          SLACK_CHANNEL: ${{ matrix.slack-channel }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
