---
name: 📟 PagerDuty Rota Notifier

on:
  schedule:
    # - cron: "0 9 * * 1-5" # Monday-Friday at 09:00 UTC
    - cron: "0 8 * * 1-5" # Monday-Friday at 08:00 UTC, or 09:00 BST
  workflow_dispatch:

permissions: {}

jobs:
  pagerduty-rota-notifier:
    name: PagerDuty Rota Notifier
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - pagerduty-schedule-id: POE95CC # Analytical Platform
            slack-channel: C04M8224WCV # analytical-platform
          - pagerduty-schedule-id: PW7Q2MF # Find MoJ Data Daily Support
            slack-channel: C03QZ776JVA # data-catalogue
          - pagerduty-schedule-id: PXQTX9B # Data Engineering Support SEO
            slack-channel: C08M8JCR1RN # de-support-pagerduty-test
          - pagerduty-schedule-id: PAMEXM1 # Data Engineering Support G7
            slack-channel: C08M8JCR1RN # de-support-pagerduty-test
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set Up uv
        id: setup_uv
        uses: astral-sh/setup-uv@c7f87aa956e4c323abf06d5dec078e358f6b4d04 # v6.0.0

      - name: Run Script
        id: run_script
        run: |
          uv run main.py
        env:
          PAGERDUTY_SCHEDULE_ID: ${{ matrix.pagerduty-schedule-id }}
          PAGERDUTY_TOKEN: ${{ secrets.PAGERDUTY_TOKEN }}
          SLACK_CHANNEL: ${{ matrix.slack-channel }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
