---
name: 🅿️ pre-commit Update

on:
  schedule:
    - cron: "0 9 * * 1-5" # Monday-Friday at 09:00 UTC
  workflow_dispatch:

permissions: {}

jobs:
  pre-commit-update:
    name: pre-commit Update
    permissions:
      contents: write
      pull-requests: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-pre-commit-update.yml@7c80b25e08b491427f45316a8c10ba44232d985f # v7.2.0
