---
name: 🅿️ pre-commit Update

on:
  schedule:
    - cron: "0 9 * * 1-5" # Monday-Friday at 09:00 UTC
  workflow_dispatch:

permissions: {}

jobs:
  pre-commit-update:
    name: pre-commit Update
    permissions:
      contents: write
      pull-requests: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-pre-commit-update.yml@f560940f48f870d54b3ce6a318d3548132c5da96 # v6.0.0
