---
name: 🦝 Super Linter

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-super-linter.yml@f560940f48f870d54b3ce6a318d3548132c5da96 # v6.0.0
    with:
      super-linter-variables: |
        {
          "LINTER_RULES_PATH": ".",
          "PYTHON_RUFF_FORMAT_CONFIG_FILE": "pyproject.toml"
        }
